[build]
  command = "npm ci && npm run build"
  publish = ".next"

  [build.environment]
    NODE_VERSION = "20"
    NPM_FLAGS    = "--prefer-offline"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
